const SessionConstants = {
  LOGIN : "LOGIN",
  LOGOUT: "LOGOUT",
  RECEIVE_PROJECTS: "RECEIVE_PROJECTS",
  RECEIVE_PROJECT: "RECEIVE_PROJECT",
  RECEIVE_SEARCH: "RECEIVE_SEARCH"
};

module.exports = SessionConstants;
