const SessionConstants = {
  LOGIN : "LOGIN",
  LOGOUT: "LOGOUT",
  RECEIVE_PROJECTS: "RECEIVE_PROJECTS",
  RECEIVE_PROJECT: "RECEIVE_PROJECT",
  RECEIVE_SEARCH: "RECEIVE_SEARCH",
  RECEIVE_INVESTMENTS: "RECEIVE_INVESTMENTS",
  RECEIVE_INVESTMENT: "RECEIVE_INVESTMENT"
};

module.exports = SessionConstants;
