json.extract! @project, :id,
                        :name,
                        :description,
                        :street_address,
                        :city,
                        :state,
                        :zip_code,
                        :media_url,
                        :author_id,
                        :archived,
                        :investment,
                        :goal
